type Constructor {
  _id: ID!
  constructorRef: String!
  name: String!
  nationality: String
  url: String
}

type Query {
  constructor(ref: String!): Constructor!
  constructors: [Constructor!]!
}
