type Driver {
  _id: ID!
  driverRef: String!
  number: Int
  code: String!
  forename: String!
  surname: String!
  dob: String!
  nationality: String!
  url: String
  results: [Result!]!
}

type Query {
  driver(ref: String!): Driver!
  drivers: [Driver!]!
}
